APB-6951 - TeamMemberRemove
hmrc/agent-permissions-frontend pull request #328
Opened 2023-03-17 16:54 UTC by raw1697

TeamMemberRemove welsh toggle

2023-03-17 17:28 UTC, CarolineS-QA requested changes

2023-03-17 17:28 UTC, CarolineS-QA commented on app/controllers/CreateGroupSelectTeamMembersController.scala
> +          result <- maybeClientId.flatMap(id => selectedMembers.getOrElse(Seq.empty).find(_.id == id)) match {
Please rename clientId to memberId? 🔍 👀

2023-03-20 10:14 UTC, geoffreywatson approved these changes

2023-03-20 10:19 UTC, CarolineS-QA approved these changes

2023-03-20 10:20 UTC, merged