ABP 7202 RW_1 Create group team members
hmrc/agent-permissions-frontend pull request #376
Opened 2023-05-23 10:41 UTC by raw1697

2023-05-23 11:12 UTC, CarolineS-QA approved these changes

2023-05-23 12:32 UTC, CarolineS-QA requested changes

2023-05-23 12:32 UTC, CarolineS-QA requested changes
👀

2023-05-24 10:10 UTC, CarolineS-QA commented on app/views/groups/create/clients/select_paginated_clients.scala.html
> +    backLinkTextKey = Some(msgs("back to search")),
You forget to add a message key for "Back to search"

2023-05-24 15:28 UTC, dg-21-hmrc commented
DO NOT MERGE

2023-05-24 16:08 UTC, closed without merging